repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        name: mypy (tmt-recipe-tool)
        files: ^tmt-recipe-tool/
        language_version: python3.9
        args: [--config-file=tmt-recipe-tool/pyproject.toml]
        additional_dependencies:
          - click>=8.0.3
          - ruamel.yaml>=0.16.6
          - tmt>=1.72
          - types-requests
